### ISSUE TITLE
Enable file storage for Directus

### ISSUE THREAD

**Issue by ChialiT** [Enaleia/Directus#11]
Using aws s3 to allow user upload files via directus app

**Comment by hemratna** [comment]
I have added the S3 bucket named **_enaleia-directus_**.
Now, all file uploads from Directus will be stored into the secured AWS S3 bucket.

**Comment by ChialiT** [comment]
@hemratna I saw the s3 bucket is enable, but when i upload files to directus, it gave me this error:

{
  "errors": [
    {
      "message": "User: arn:aws:iam::034362072671:user/enaleia-directus-s3-user is not authorized to perform: s3:ListBucket on resource: \"arn:aws:s3:::enaleia-directus\" because no identity-based policy allows the s3:ListBucket action",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

**Comment by hemratna** [comment]
@ChialiT,
The issue has been resolved.

Now, You will able to do upload / replace / delete file from the Directus to the S3 bucket.

**Comment by ChialiT** [comment]
now we can access all the file functions via directus ui.
