### ISSUE TITLE
Develop custom logic on directus : Calculate

### ISSUE THREAD

**Issue by ChialiT** [Enaleia/Directus#6]
After linking the input and output event, calculate the percentage of the plastic from each port into the Kayak making.
Will need to collab with Product QR webpage 

**During Pelletization**

A pelletization event is normally outputting 10 tons, of which 20% are generally ocean plastics, but we still need to make the calculation as follow to insure accuracy.

**During Manufacturing**

Kayak manufacturing will possibly use multiple pellet batches and because some batch might not be used completely, the manufacturing user will have entered weights used per batches.

1. X= sum weights used as entered by user for each pellet batches **input_qr**
2. (X/(output_weight*batch_quantity))*100 = percentage of ocean plastics used for this Kayak batch.

**Comment by Thatsocool** [comment]
Please disregard previous calculation as they are erroneous, instead refer to the following WIP calcualtion in [**Figjam**](https://www.figma.com/board/CJqXAUt1A7HAgLsM7fr9mU?node-id=2385-20823#990861173)

**Comment by ChialiT** [comment]
Due of the complexity from the operational, we will close this issue and mark as WONT DO
